### ISSUE TITLE
Publish chart to a public helm repository

### ISSUE THREAD

**Issue by JonnyBGod** [stakater/IngressMonitorController#107]
Get IMC listed in the public helm repository i.e. https://github.com/helm/charts

**Comment by rasheedamir** [comment]
@JonnyBGod we do publish IngressMonitorController chart here in this public repository https://github.com/stakater/stakater-charts

Is that what you are looking for? 

Or you think we should publish them here as well: https://github.com/helm/charts

**Comment by JonnyBGod** [comment]
That should be fine for me.

But you should document that.

It might increase adoption though if you publish it to https://github.com/helm/charts

**Comment by rasheedamir** [comment]
Yeah agreed @JonnyBGod we will definitely do that!

Also we are going to update the README and make it clear for user how to easily find the charts.

**Comment by ahmadiq** [comment]
Hi @JonnyBGod We have documented the steps for using our Stakater Charts repository here:
https://github.com/stakater/IngressMonitorController#helm-charts

**Comment by JonnyBGod** [comment]
Perfect

**Comment by boxcee** [comment]
@ahmadiq The documentation at https://github.com/stakater/IngressMonitorController#helm-charts points to the wrong repo, which is not updated at the moment. It still runs app version v1.0.47.

I think the documentation should point to https://github.com/stakater/stakater-charts or the chart should automaticall be uploaded to https://github.com/helm/charts, which was already addressed in #125.
