### ISSUE TITLE
Add chart to official helm/stable repo

### ISSUE THREAD

**Issue by monotek** [stakater/IngressMonitorController#125]
Please add the chart (https://github.com/stakater/IngressMonitorController/tree/master/deployments/kubernetes/chart/ingressmonitorcontroller) to https://github.com/helm/charts/tree/master/stable.

Imho people will look there first for a chart.

**Comment by rasheedamir** [comment]
great idea @monotek we will do that!

**Comment by monotek** [comment]
It's there :-)
https://github.com/helm/charts/pull/8975

**Comment by rasheedamir** [comment]
@faizanahmad055 update the README and include how one can install using the helm chart; seems to be currently missing.

**Comment by faizanahmad055** [comment]
Readme update is being tracked in #131. IMC chart has been submitted to official helm repo so closing this issue.
