### ISSUE TITLE
Monitor not deleted upon removing Ingress

### ISSUE THREAD

**Issue by hazim1093** [stakater/IngressMonitorController#127]
**Kubernetes Version**:  1.10.8
**Ingress Monitor Controller Version**: 1.0.26
**Provider**: Uptime Robot

Deleted a service and ingress with IMC annotation, but it did not delete the monitor in Uptime Robot.
The logs for IMC were as follows: 

```
2018/11/05 12:38:24 Get service from kubernetes cluster error:services "example-ws" not found
2018/11/05 12:38:24 Monitor Name: prod-example-ws
2018/11/05 12:38:24 Monitor URL: https://example.com/public/example/0.1
2018/11/05 12:38:24 Monitor already exists for ingress: prod-example-ws
2018/11/05 12:38:24 Monitor Updated: prod-example-ws
```

**Comment by rasheedamir** [comment]
This has been taken care in new operator based version starting from **2.0.0**
