### ISSUE TITLE
Add support for Azure Application Insights in IMC

### ISSUE THREAD

**Issue by sabbour** [stakater/IngressMonitorController#130]
Add support for Azure Application Insights in IMC to monitor the uptime of web applications / microservices deployed to kubernetes/openshift

https://docs.microsoft.com/en-us/azure/application-insights/app-insights-monitor-web-app-availability
https://azure.microsoft.com/en-us/blog/creating-a-web-test-alert-programmatically-with-application-insights/
https://docs.microsoft.com/en-us/rest/api/application-insights/webtests/createorupdate

Conventions to follow: https://github.com/stakater/IngressMonitorController/blob/master/docs/developing/contributing.md

**Comment by rasheedamir** [comment]
@sabbour it will be awesome if we can add support for it; I wonder if you can work on it? We will help you out.

**Comment by sabbour** [comment]
I added it as a placeholder, and I’ll have a look at it ☺

- Ahmed

**Comment by rasheedamir** [comment]
@sabbour i wonder if there is any free tier that can be used when one wants to implement support of Azure Application Insights in IMC?

**Comment by sabbour** [comment]
@rasheedamir Application Insights ping web tests are free https://azure.microsoft.com/en-us/pricing/details/monitor/
