### ISSUE TITLE
Add support for Stackdriver Uptime Checks and Alert Policies in IMC

### ISSUE THREAD

**Issue by linki** [stakater/IngressMonitorController#140]
Add support for Stackdriver Uptime Checks and Alert Policies in IMC to monitor the uptime of web applications / microservices deployed to kubernetes/openshift

Uptime checks:
* https://cloud.google.com/monitoring/uptime-checks/

Alert Policies:
* https://cloud.google.com/monitoring/uptime-checks/uptime-alerting-policies

Golang client library:
* https://godoc.org/cloud.google.com/go/monitoring/apiv3
* https://godoc.org/google.golang.org/genproto/googleapis/monitoring/v3
* code examples:
  * UptimeCheck example: https://github.com/GoogleCloudPlatform/golang-samples/blob/master/monitoring/uptime/uptime.go
  * Alert Policy example: https://github.com/GoogleCloudPlatform/golang-samples/blob/master/monitoring/alert/alert.go

**Comment by rasheedamir** [comment]
@linki do you think you can create a PR for this?

**Comment by linki** [comment]
Do you have some guidance how to add another monitoring solution, e.g. which existing one would be a good starting point, what interface to implement, what to look out for in general?

**Comment by rasheedamir** [comment]
https://github.com/stakater/IngressMonitorController/blob/master/CONTRIBUTING.md#adding-support-for-a-new-monitor

Hopefully it's updated and should be a good starting point and also we are on slack

**Comment by linki** [comment]
Thanks!

**Comment by maennchen** [comment]
Status Update: With #254, support for Uptime Checks should be done. The alert policies are not done yet.
