### ISSUE TITLE
IngressMonitorController should update URL on pod changes

### ISSUE THREAD

**Issue by xanonid** [stakater/IngressMonitorController#147]
Currently, it seems that IngressMonitorController discovers the URLs to be monitored only at startup or on Ingress changes.

If the readiness URLs of the pods behind a ingress changes, the URLs are not updated automatically.

The issue could be solved by doing regularly a full-scan of all monitors and update the URLs if necessary.
My suggestion would be to try simply a resyncPeriod > 0 in 
https://github.com/stakater/IngressMonitorController/blob/2c627d18163c00b2826c694b78c770ba3eae509f/pkg/controller/controller.go#L53

**Comment by rasheedamir** [comment]
@xanonid can you please create a PR for this change?
