### ISSUE TITLE
Add support for integrations in Pingdom

### ISSUE THREAD

**Issue by sharkymcdongles** [stakater/IngressMonitorController#158]
The check api definitions are here:

https://www.pingdom.com/api/2.1/#MethodCreate+New+Check

Basically, we need to be able to specify the integration ids for checks to allow checks created by the controller to have integration features.

integrationids | Integration identifiers. For example integrationids=11,22,33 | Comma separated Integers

The work is minimal, so I will see if I can submit a PR unless someone more familiar wants to do it.

**Comment by rasheedamir** [comment]
@sharkymcdongles that will be awesome if you can submit a PR!

**Comment by kahootali** [comment]
@sharkymcdongles @rasheedamir, FYI @boxcee is working on it and has created a PR, some tests are failing, we are working on them, it will be fixed by today most probably

**Comment by aliartiza75** [comment]
the fix has been pushed,

#### `Test fail reasons`
In config tests test oracle was not being constructed correctly.
