### ISSUE TITLE
Use constants for statusCodes

### ISSUE THREAD

**Issue by aliartiza75** [stakater/IngressMonitorController#159]
Currently, hard code values for the status code are being used like `200` and `404` etc, which is not easy to understand(for beginners) and error-prone(because we might need to updated all files for a single status code change). 

### `OLD SOLUTION`
Instead of hard code values, constants must be used. A map has been defined in the `pkg/constants`  that contains the constants for status codes.

`filename:` httpStatusCodesMap.go 
```go
var StatusCodes = map[string]int{
	"OK":            200,
	"NOT_FOUND":     404,
	"UN_AUTHORISED": 401,
	"BAD_REQUEST":   400,
	"CREATED":       201}

```

### `NEW SOLUTION`

Based on @waseem-h suggestion, go's `net/http` package [constants](https://golang.org/pkg/net/http/#pkg-constants) will be used for response codes.

This change must be applied to all IMC modules.

**Comment by waseem-h** [comment]
@aliartiza75 You don't need a custom map for status codes. Go's `http` package has all of the status codes defined as a constant which you should use everywhere. https://golang.org/pkg/net/http/#pkg-constants

Just remove the above and use `http.StatusOK`, `http.StatusCreated` and so on

**Comment by aliartiza75** [comment]
@waseem-h based on your suggestion, I have updated the issue

**Comment by DhiaTN** [comment]
I've submitted a PR to replace the hard coded values here: #171

**Comment by usamaahmadkhan** [comment]
#189 to apply this to all monitors
