### ISSUE TITLE
Add structured logging

### ISSUE THREAD

**Issue by lumberj** [stakater/IngressMonitorController#166]
Something like https://github.com/sirupsen/logrus. We run many different components internally, and use Datadog to monitor our logs for errors, etc. Having machine parseable logs (e.g., key=value, json) along with log levels.

I think this should be a simple drop in replacement,

> Logrus is a structured logger for Go (golang), completely API compatible with the standard library logger.

By default, the Go logger logs to stderr, so by default everything shows up in my log aggregator at error level.

**Comment by waseem-h** [comment]
I had plans to replace old logging a while ago. Good that you brought it up again @lumberj. I'll see if I can do it soon.

**Comment by rasheedamir** [comment]
@lumberj would you like to make a PR?

**Comment by lumberj** [comment]
Sure I can look into it

**Comment by lumberj** [comment]
I just pushed a PR that only replaces the standard logger. I want to also be able to change the logging format and log level. This is probably best done via env variables (e.g., LOG_LEVEL, LOG_FORMAT). What do you think?
