### ISSUE TITLE
ClusterRoleBinding section defined twice

### ISSUE THREAD

**Issue by SunSparc** [stakater/IngressMonitorController#167]
I was reviewing the `ingressmonitorcontroller.yaml` file to possibly use for my cluster. I found that the `ClusterRoleBinding` section was duplicated. Is this intentional?

You can see it first [here at line 140](https://github.com/stakater/IngressMonitorController/blob/master/deployments/kubernetes/ingressmonitorcontroller.yaml#L140) and then again immediately after [at line 155](https://github.com/stakater/IngressMonitorController/blob/master/deployments/kubernetes/ingressmonitorcontroller.yaml#L155).

**Comment by rasheedamir** [comment]
Thanks @SunSparc this must be a bug; you want to create a PR?

**Comment by SunSparc** [comment]
I just noticed that the `ClusterRole` is also duplicated. I wonder if the problem is somewhere else. This file is built from templates, correct?

**Comment by SunSparc** [comment]
Oh, it looks like everything that came from `# Source: ingressmonitorcontroller/templates/rbac.yaml` is duplicated elsewhere.

**Comment by kahootali** [comment]
@SunSparc This issue has been fixed in [PR#169](https://github.com/stakater/IngressMonitorController/pull/169). 
Thanks for contributing.
