### ISSUE TITLE
Add contribution guide

### ISSUE THREAD

**Issue by DhiaTN** [stakater/IngressMonitorController#175]
That would be amazing if the project has a contribution guide that makes it easier to contribute and run tests locally. I'm trying to run tests on master branch but it's already failing, so I'm not able to check wether my PRs or any change has broken something:
=> [Adding a Contributing File](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors#adding-a-contributing-file)

**Comment by rasheedamir** [comment]
Very good idea @DhiaTN ; we must have one; can you make a PR?

**Comment by DhiaTN** [comment]
> Very good idea @DhiaTN ; we must have one; can you make a PR?

@rasheedamir @usamaahmadkhan I need your help for that, as I'm failing to run tests locally and I couldn't find why.

**Comment by usamaahmadkhan** [comment]
@DhiaTN  You need to set **CONFIG_FILE_PATH** variable. Refer to **GetControllerConfig()** method in **pkg/config/config.go**. Set your config file through this environment variable and then run the tests. I'll add the steps in docs as well.

**Comment by usamaahmadkhan** [comment]
Contribution guide added as CONTRIBUTION.md by #178
