### ISSUE TITLE
IMC creates the same alert if the pod is restarted

### ISSUE THREAD

**Issue by grebois** [stakater/IngressMonitorController#182]

**Comment by grebois** [comment]
Not sure how this works https://github.com/stakater/IngressMonitorController/blob/ce3e93222ca95d6c7173f7e8d438be2b5522a2d4/pkg/controller/actions.go#L71-L79

**Comment by usamaahmadkhan** [comment]
@grebois  can you provide some detailed description about this issue? thanks

**Comment by grebois** [comment]
@usamaahmadkhan sure, lets say I have only one alert, and then I restart IMC pod, when it starts, it creates a second alert for the same ingress/service but with another alert ID, at least with StatusCake.

**Comment by usamaahmadkhan** [comment]
@grebois  im unable to produce the bug you are reporting. I  reproduced the same scenario by adding an alert from statusCake. Then I restarted IMC and statusCake did not create a duplicate alert. rather it is just updating the existing monitor.
Here are the logs:

> 2019/07/08 12:54:53 Reading YAML Configuration /home/usama/Desktop/Office/ImportantConfigFiles/config.yaml
2019/07/08 12:54:56 Starting Ingress Monitor controller
2019/07/08 12:54:56 Monitor Name: mongodb-test
2019/07/08 12:54:56 Monitor URL: http://mongo.stakater.com/test%3Fkey=value
2019/07/08 12:54:57 Monitor already exists for ingress: mongodb-test

This part here takes care of duplication/updation:
https://github.com/stakater/IngressMonitorController/blob/25dd8402271d84f83428666a8e36ba64bc169e80/pkg/controller/controller.go#L181-L199

IMC version: v1.0.85

**Comment by usamaahmadkhan** [comment]
@grebois did you get a chance to look into this?

**Comment by grebois** [comment]
No, I did not, sorry, will close this for now and re-open it in case It happens again, thanks for looking up on this.
