### ISSUE TITLE
IMC only create the alert in StatusCake even when UptimeBot is configured

### ISSUE THREAD

**Issue by grebois** [stakater/IngressMonitorController#183]

**Comment by usamaahmadkhan** [comment]
@grebois not able to reproduce this. I created an Ingress monodb-test, configured both UptimeRobot and StatusCake. restarted IMC and it successfully added monitor in both of them i.e. UptimeRobot and StatusCake.

Here are the logs:

> 2019/07/08 13:20:03 Reading YAML Configuration /home/usama/Desktop/Office/ImportantConfigFiles/config.yaml
2019/07/08 13:20:06 Starting Ingress Monitor controller
2019/07/08 13:20:09 Monitor Name: mongodb-test
2019/07/08 13:20:09 Monitor URL: http://mongo.stakater.com/test%3Fkey=value
INFO[0006] Monitor Added: mongodb-test     // From StatusCake                  
INFO[0007] Monitor Added: 5055065            // From UptimeRobot

This part here takes care of this scenario:
https://github.com/stakater/IngressMonitorController/blob/25dd8402271d84f83428666a8e36ba64bc169e80/pkg/controller/controller.go#L174-L179

IMC version: v1.0.85

**Comment by grebois** [comment]
Regretfully I have no env where I can test this right now, so I will take a leap of faith and close this issue.

If I stumble upon this situation again and/or find a way to replicate this behavior in production/vacuum I'll re-open it.
