### ISSUE TITLE
Allow a delay between Ingress creation and monitor creation

### ISSUE THREAD

**Issue by lumberj** [stakater/IngressMonitorController#184]
When deploying a new service, DNS updates can take some time to propagate. We typically start getting alerts from uptimerobot right away so we have to either manually pause alerts from uptimerobot, or, apply the Ingress configuration twice (once without the annotation and then again with it).

It would be helpful to have a delay that can be configured either as a duration or timestamp (e.g., wait until X)

**Comment by rasheedamir** [comment]
great suggestion @lumberj ! looking forward for a PR
