### ISSUE TITLE
Request: Possibility to specify the type of monitor for uptimerobot (http or keyword)

### ISSUE THREAD

**Issue by e9169** [stakater/IngressMonitorController#190]
In uptimerobot you can create different type of monitors. You can create http(s) (the ones supported by IMC), based on keywords, which is something really useful when you have health checks, and others like ping or port.

Could you please implement this feature (at least keyword) into IMC?

Thank you

**Comment by usamaahmadkhan** [comment]
@e9169 It will be a nice feature to add. We will add it into our backlog and of course all PRs are welcome.

**Comment by e9169** [comment]
@usamaahmadkhan I'd happy to do the modifications and create the PR. However, I've been looking at the code and have some basic questions before I can proceed. Sorry but this would be my first contact with Go, never touched it before. Here we go:

I though that a good approach for this would be to specify a monitor type by default, let's say 1 (for http) and then the user could easily overwrite this parameter with an annotation on the ingress since we don't want all monitors to be of one type only. If we use type 2 (keyword), then two additional parameters have to be used and passed through the API: keyword_type and keyword_value. These, I think, could be as well annotations since it might vary from monitor to monitor. 

Now for the coding part: Should I update config.go to add a "Type" field (int) mapping to the yaml file? Besides that, where exactly in the code should I add these annotations? uptime-monitor.go? What about the controller.go and actions.go files? Should I modify them as well? I'm trying to find out all these things while reading at the code but a few hints would be really appreciated. 

Thank you

**Comment by usamaahmadkhan** [comment]
@e9169 yes the ideal way to do it would be to use the default type as HTTP (i.e. type=1) so that the changes are not breaking and can be overridden as per needed. You can see the annotations being overridden here. This would be enough for you to backtrack and add another annotation:
https://github.com/stakater/IngressMonitorController/blob/101f55515bcfd0bebaf0c40d2d78ca9580b0dcee/pkg/monitors/uptimerobot/uptime-monitor.go#L87-L98

config_test.go would ensure that the passed config of Uptimerobot is correct. (templates in configs/testConfigs). Most of the changes would be required in pkg/monitors/uptimerobot/uptime-monitor.go

**Comment by e9169** [comment]
> @e9169 yes the ideal way to do it would be to use the default type as HTTP (i.e. type=1) so that the changes are not breaking and can be overridden as per needed. You can see the annotations being overridden here. This would be enough for you to backtrack and add another annotation:
> 
> https://github.com/stakater/IngressMonitorController/blob/101f55515bcfd0bebaf0c40d2d78ca9580b0dcee/pkg/monitors/uptimerobot/uptime-monitor.go#L87-L98
> 
> config_test.go would ensure that the passed config of Uptimerobot is correct. (templates in configs/testConfigs). Most of the changes would be required in pkg/monitors/uptimerobot/uptime-monitor.go

Thank you @usamaahmadkhan 

If I do 	

```
if val, ok := m.Annotations["uptimerobot.monitor.stakater.com/monitor-type"]; ok {
		body += "&type=" + val 
	}
```

Am I rewriting the type in here `body := "api_key=" + monitor.apiKey + "&format=json+&type=1&url="` or am I adding a new '&type' to the API request? This part is unclear for me yet.

**Comment by usamaahmadkhan** [comment]
No. Right now `type=1` is hardcoded in the `body`. You need to remove that and append the value.

**Comment by e9169** [comment]
@usamaahmadkhan The PR here: [https://github.com/stakater/IngressMonitorController/pull/193](url)
