### ISSUE TITLE
Not able to List Ingresses

### ISSUE THREAD

**Issue by Berndinox** [stakater/IngressMonitorController#212]
`E1025 10:28:35.348694       1 reflector.go:205] pkg/mod/k8s.io/client-go@v6.0.1-0.20180103015815-9389c055a838+incompatible/tools/cache/reflector.go:99: Failed to list *v1beta1.Ingress: ingresses.extensions is forbidden: User "system:serviceaccount:uptimerobot:ingressmonitorcontroller" cannot list resource "ingresses" in API group "extensions" at the cluster scope
`

K8s 1.15.5

Install via:

`kubectl apply -f https://raw.githubusercontent.com/stakater/IngressMonitorController/master/deployments/kubernetes/ingressmonitorcontroller.yaml -n=uptimerobot`

**Comment by usamaahmadkhan** [comment]
@Berndinox ingressmoitorcontroller is working fine on k8s version 1.13.* .I have tested on a minkube 1.15 instance and facing the same issue. will keep you posted on this thread.

**Comment by rasheedamir** [comment]
@Berndinox this issue has been fixed in the latest release; please give it a try; for now I am closing this issue and you can re-open: https://github.com/stakater/IngressMonitorController/releases/tag/v2.0.0
