### ISSUE TITLE
Pingdom: Make alertContacts configurable from annotation

### ISSUE THREAD

**Issue by zonorti** [stakater/IngressMonitorController#222]
When using IMC with Pingdom we want to route alerts to different contacts depending on the service.
It is currently possible to use an annotation for custom integration, but not for the contact.
Probably something close to https://github.com/stakater/IngressMonitorController/blob/master/pkg/monitors/pingdom/pingdom-monitor.go#L168
Thanks!

**Comment by rasheedamir** [comment]
Yeah correct @zonorti ! PR's are more than welcome

**Comment by zonorti** [comment]
Closed in #228, thanks @tuananhnguyen-ct
