### ISSUE TITLE
Helm Chart doesnt support creationDelay or resyncPeriod

### ISSUE THREAD

**Issue by jseiser** [stakater/IngressMonitorController#223]
The helm chart, doesnt provide the ability to set these options.

**Comment by jseiser** [comment]
https://github.com/helm/charts/pull/19996

**Comment by jseiser** [comment]
Any assistance on getting the above merged would be great.

**Comment by rasheedamir** [comment]
@jseiser sorry for the delay; i have approved it now

**Comment by jseiser** [comment]
@rasheedamir 

Thanks.

Im getting caught up on this

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/19996/pull-charts-e2e/1221860926861348864/

Im not sure how to even fix that.

**Comment by rasheedamir** [comment]
strange; @kahootali any idea what could be wrong?

**Comment by usamaahmadkhan** [comment]
@jseiser since 1.0.56 the image tag is prefixed with **v** so the tag should be **v1.0.92** . e2e job cannot find the tag 1.0.92 from the image registry.

**Comment by kahootali** [comment]
@jseiser Sorry for the delay, but as helm/charts is deprecating, so we don't update the public chart frequently. Rather as the chart is hosted in this repo so we recommend using this because it has all the latest changes and is updated whenever a new feature/bugfix is released.

**Comment by jseiser** [comment]
@kahootali 

Any chance you guys will host the chart, not in the git repo?  I only ask, because we use Weave Flux, and i dont want to have to manage adding a SSH key to it to clone straight from git.

If not, Its not a problem I can host it internally on our chart museum.

**Comment by kahootali** [comment]
@jseiser We have hosted the chart, it is present at [stakater-charts](https://stakater.github.io/stakater-charts/)
I will update the README and add this repo in the helm section
