### ISSUE TITLE
Add instructions for installation via helmfile

### ISSUE THREAD

**Issue by RobertTownley** [stakater/IngressMonitorController#251]
There are great docs in place for installing the required IMC resources via a k8s manifest, or via a `helm install` command. But for users managing the deployment of their helm charts within helmfile, it could be helpful to have a documented example of what a helmfile for the IMC can look like, since the formatting for overriding values differs from a normal helm or k8s apply installation.

**Comment by usamaahmadkhan** [comment]
@RobertTownley are you looking for these? https://github.com/stakater/IngressMonitorController/blob/master/deployments/kubernetes/chart/ingressmonitorcontroller/README.md
