### ISSUE TITLE
Using Uptime Robot interval annotation stops monitor creation

### ISSUE THREAD

**Issue by domhdp** [stakater/IngressMonitorController#257]
We are using IngressControllerMonitor in production, and have an upgraded Uptime Robot account that allows for monitoring intervals down to 1 minute.

When we use the annotation `uptimerobot.monitor.stakater.com/interval` with a value of "1" I noticed from the logs that the monitors were not being created. When I remove this annotation the monitor was created as expected.

I haven't looked into the code yet to understand, but I could not get more leg messages with "debug" and "info" LOG_LEVELs.

Is there any reason for this?

**Comment by twardnw** [comment]
Per the Uptime Robot API, this should be a value in seconds

> monitor>interval | integer | the interval for the monitoring check (300 seconds by default).

https://uptimerobot.com/api

**Comment by domhdp** [comment]
@twardnw Ah of course. I should have sent to 60.

Thanks!
