### ISSUE TITLE
how to structure multiple values for uptime robot status pages

### ISSUE THREAD

**Issue by twardnw** [stakater/IngressMonitorController#258]
I am working on an improvement to the Uptime Robot integration to allow for a monitor to be added to multiple status pages (at Uptime Robot). The Uptime Robot API does not allow for this directly, so in uptime-monitor.go i will need to iterate a list of page IDs that a monitor should be added to. 

As such, my question is about how to structure this list of IDs in the `uptimerobot.monitor.stakater.com/status-pages` annotation. This could easily be any structure though, comma-delimited, a JSON array, etc. My first inclination though is to follow the structure that the Uptime Robot API has for multiple alert contacts on a monitor, a dash-delimited list. Looking for thoughts and input as I prepare my PR for this.

**Comment by waseem-h** [comment]
We already have alert contacts separated by hyphens which is what Uptime robot supports. So its better to use the same for any other annotation that needs to be a list and is specific to Uptime robot @twardnw

**Comment by twardnw** [comment]
Thanks @waseem-h , I'll have a PR relating to this shortly for you all :)
