### ISSUE TITLE
Add helm chart for operator

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [stakater/IngressMonitorController#268]
With migration from controller to operator, we removed the helm chart out of the operator. Add helm chart back again since it's required for ease of use.

**Comment by onedr0p** [comment]
This would be amazing, thanks!

**Comment by invidian** [comment]
There is some chart here: https://github.com/helm/charts/tree/master/stable/ingressmonitorcontroller, but the stable repo is deprecated, so it would be nice to have chart adopted here.

**Comment by magneticz** [comment]
Hi all, i've been working on IMC at my work and created initial version of the helm chart for our use based on old helm chart and resource definitions in `./deploy` folder. Now, I am new to kubernetes and helm, but I would be happy to create PR and refine the chart with your help. Would you guys be interested in PR?

If yes, another question would be where should I create the PR? As @invidian  pointed out, charts at helm/charts are deprecated and updates are no longer accepted. Should the chart be created here?

**Comment by rasheedamir** [comment]
PR's are always welcome @magneticz!

We will be hosting our charts here: https://github.com/stakater/stakater-charts

**Comment by magneticz** [comment]
@rasheedamir great, then you can assign this issue to me, i will create PR soon
