### ISSUE TITLE
StatusCake statuscode configuration not implemented

### ISSUE THREAD

**Issue by llivingstone** [stakater/IngressMonitorController#292]
Hi,

Is there a reason why that the `providerConfig.StatusCodes` is not used inside the StatusCake implementation?

https://github.com/stakater/IngressMonitorController/blob/master/pkg/monitors/statuscake/statuscake-monitor.go#L83

The API seems to support a comma separated list of statuscodes to alarm on as per https://www.statuscake.com/api/Tests/Updating%20Inserting%20and%20Deleting%20Tests.md

I'll try to come up with a MR when i have the time.

**Comment by ahmedwaleedmalik** [comment]
Hi @llivingstone, there is no specific reason for it being missing but yes it should have been implemented. PR for this would be a great addition :)

**Comment by llivingstone** [comment]
@ahmedwaleedmalik Great, I should have some time next week to come up with a PR 👍

**Comment by llivingstone** [comment]
Hi @ahmedwaleedmalik, Just an update that we should have some time for this soon on our scope to make a PR regarding this.

**Comment by llivingstone** [comment]
https://github.com/stakater/IngressMonitorController/pull/298/files

**Comment by llivingstone** [comment]
Hi @ahmedwaleedmalik - any update on the PR?

**Comment by llivingstone** [comment]
Hi @ahmedwaleedmalik - Any update on this one?

**Comment by ahmedwaleedmalik** [comment]
Hi @llivingstone, should be good to go now. I have merged the PR.

**Comment by llivingstone** [comment]
Perfect, thank you @ahmedwaleedmalik!
