### ISSUE TITLE
Monitor not update on uptimerobot side

### ISSUE THREAD

**Issue by talha0324** [stakater/IngressMonitorController#303]
**Scenario:** 
I have a endpoint monitor added to my CRDs, lets say endpoint `abc`. Now I update my endpoint monitor definition in CRD. IMC logs that `abc` monitor is updated.

**Issue:** 
Monitor `abc` is never updated in uptime robot, unless you delete it manually.

**Workaround:** 
I have to manually delete the monitor `abc` from updtime robot , then IMC creates a new entry of `abc` monitor in uptime robot.

**Comment by ahmedwaleedmalik** [comment]
That's a very vague description. Can you be more specific with examples ?

**Comment by ahmedwaleedmalik** [comment]
@talha0324 Can i close this?

**Comment by talha0324** [comment]
Sure.
