### ISSUE TITLE
Download link of ingressmonitorcontroller.yaml is not working

### ISSUE THREAD

**Issue by pravin-d-patil** [stakater/IngressMonitorController#345]
Hi,

I want to download ingressmonitorcontroller.yaml file but it's download link is not working.
Here is the link provided: 
https://raw.githubusercontent.com/stakater/IngressMonitorController/master/deployments/kubernetes/ingressmonitorcontroller.yaml

Kindly point me to correct download link.

Thank you.

**Comment by ahmedwaleedmalik** [comment]
Hi @pravin-d-patil, thank you for pointing us to this issue. Although this is not the recommended way to install IMC anymore and this link only exists in `v1.x.x` of IMC. Which is something we don't maintain anymore. 

Please take a look at this guide for deploying the operator:

[Deploying IngressMonitorController](https://github.com/stakater/ingressMonitorController#deploying-the-operator)
