### ISSUE TITLE
[chart] Wrong `gcr.io/kubebuilder/kube-rbac-proxy` tag

### ISSUE THREAD

**Issue by cwrau** [stakater/IngressMonitorController#346]
In the helm chart version `2.1.8` the `gcr.io/kubebuilder/kube-rbac-proxy` image has a tag of `v2.1.8` which is of course wrong

It should probably be `v0.8.0`, the latest release

**Comment by ahmedwaleedmalik** [comment]
@cwrau that was a bug that is fixed in the latest release. Apologies for any inconvenience.

**Comment by cwrau** [comment]
Thanks for the fix!
