### ISSUE TITLE
Pingdom - SSLDownDaysBefore needs VerifyCertificate

### ISSUE THREAD

**Issue by mkoszut** [stakater/IngressMonitorController#367]
`SSLDownDaysBefore` default value for this option is `28` days. But to enable this option in Pingdom `SSLDownDaysBefore` should be set on `true`. Without that, in IngressMonitorController logs we can observe an error like below.

```
{"level":"info","ts":1635924486.6544814,"logger":"pingdom","msg":"Error updating Monitor: 400 Bad Request: Parameter `ssl_down_days_before` requires `verify_certificate` to be active"}
```

**Comment by jsokol89** [comment]
I've bumped into the same issue.
The https://github.com/stakater/IngressMonitorController/pull/370 pull request fixes it.
