### ISSUE TITLE
Google Cloud Test Project went rogue

### ISSUE THREAD

**Issue by maennchen** [stakater/IngressMonitorController#405]
Hi,

I've deleted the google cloud test project which was used in the tests.

For some reason, the monthly costs went from basically nothing until September to over 2'000 $ in October.

I'm contacting google to figure out exactly what happened. In the meantime, the credentials will no longer work.

**Comment by karl-johan-grahn** [comment]
What happened?

**Comment by maennchen** [comment]
Somehow the cleanup of the checks was not working and there was thousands of checks running leading to a massive invoice.
