### ISSUE TITLE
Chart shouldn't create namespaces by default

### ISSUE THREAD

**Issue by hgranillo** [stakater/IngressMonitorController#411]
I noticed that the current behavior of the chart is to create and manage a namespace when it is installed, and delete the namespace when it is uninstalled. It seems like an anti-pattern to me and I believe it would be more user-friendly if this behavior were optional.

Currently, the `namespace` chart value is set to `stakater-ingress-monitor-controller` in the `values.yaml` file (https://github.com/stakater/IngressMonitorController/blob/master/charts/ingressmonitorcontroller/values.yaml#L90), which means that if I install the chart and set the namespace value to a namespace where I have other services running, and then later decide to uninstall the chart, it would delete the entire namespace.

I suggest changing the chart to  always use  `{{ .Release.Namespace }}`, which would allow the user to specify the target namespace for the chart installation as a helm parameter instead of a chart parameter. This is similar to the behavior of previous versions of the chart.

If the maintainers prefer to keep the current namespace creation feature, I suggest adding some if clauses to the namespace.yaml template (https://github.com/stakater/IngressMonitorController/blob/master/charts/ingressmonitorcontroller/templates/namespace.yaml) to give the user more control over this behavior.

I would be happy to create a pull request to address these issues if the maintainers agree.

**Comment by karl-johan-grahn** [comment]
Closed in favor of https://github.com/stakater/IngressMonitorController/pull/441
