### ISSUE TITLE
Add pingdom support

### ISSUE THREAD

**Issue by jasongwartz** [stakater/IngressMonitorController#44]
Saw the Medium article, great tool!

We use Pingdom, which also has a decent API (though a fair bit different from the UptimeRobot API).

If this isn't already in the works, I'll have a crack at it :smile:  - seems like there might be some changes needed to the httpClient layer to make it happen.

**Comment by rasheedamir** [comment]
@jasongwartz please go ahead and crack it! currently we don't have any plans to support pingdom but will be very happy if you can help us to add it.

**Comment by mmiller1** [comment]
@jasongwartz have you started any work towards this? I'd be willing to chip in as well to see this happen.

**Comment by jasongwartz** [comment]
@mmiller1 great! I started to take a look at it a few days ago. The httpClient is written pretty exclusively for UptimeRobot, and large parts of it need to be rewritten to work with the Pingdom API - it currently only implements POST, and Pingdom needs both POST and GET, as well as requiring HTTP Basic Auth in addition to an API token parameter. There's also a big chunk of work to model all the Pingdom API responses as structs to be unmarshaled.

When I get a chance, I'll push my current work (not yet running) up to my fork, so you can take a look at it and extend if possible.

**Comment by ahmadiq** [comment]
@mmiller1 Cool. If you can create a pull request the team can review and test with uptime robot as well.

**Comment by mmiller1** [comment]
I've tested your branch, the monitors are created, but with the incorrect host / path (pingdom defaults the check to https://google.com if none is parsed). I'll see if I can figure out what's going in your branch over the next day or so.

**Comment by waseem-h** [comment]
Closed with #55

**Comment by rasheedamir** [comment]
@mmiller1 is it working as expected or you still see some issues?
