### ISSUE TITLE
Support for arm64 image

### ISSUE THREAD

**Issue by gothka** [stakater/IngressMonitorController#505]
Hi, i'm checking to see if there's any plan to start supporting arm64 builds for the controller image as i couldn't any tag that supports that on [docker hub](https://hub.docker.com/r/stakater/ingressmonitorcontroller/tags). I'm happy to submit a PR :)

**Comment by MuneebAijaz** [comment]
hi @gothka , would you like to submit a PR for the suggested change? We do have binaries pushed for some architectures, but images are based on one arch

**Comment by tuxpeople** [comment]
I'm interested as well, but can't do a pr as I don't know anything about goreleaser, which you are using for the releases. I've only experience building multi-arch images using the docker or buildah actions.

@gothka I'm happy to test arm64 once you have such an image

**Comment by nohant** [comment]
yeah, we need that too, i think it should also need some edit on the github action because here:
```- name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ env.DOCKER_FILE_PATH  }}
        pull: true
        push: true
        cache-to: type=inline
        tags: |
          ${{ env.IMAGE_REPOSITORY }}:${{ steps.generate_tag.outputs.new_tag }}
        labels: |
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.created=${{ steps.prep.outputs.created }}
          org.opencontainers.image.revision=${{ github.sha }}
```
its only setting the default version. But by the look of it, the build version is configurer inside the dockerfile here:
`RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -mod=mod -a -o manager main.go`

**Comment by nohant** [comment]
@tuxpeople I'm sorry, you have to build locally from the branch, the default pipeline don't build for arm.
Thanks for your eventual time.

**Comment by nohant** [comment]
May i help in any other way?
its been a week and we would like to use this component in our arm cluster.

**Comment by bnallapeta** [comment]
@nohant I will take a look at this and get back to you soon.

**Comment by bnallapeta** [comment]
@nohant I just replied on #526. Please check.

**Comment by MuneebAijaz** [comment]
https://github.com/stakater/IngressMonitorController/pull/526 i suppose issue was fixed in the mentioned PR, please reopen the issue if any concerns.
