### ISSUE TITLE
RBAC: Cluster role vs per-namespace role

### ISSUE THREAD

**Issue by Mikulas** [stakater/IngressMonitorController#51]
Would you accept a PR with a `ClusterRole` instead of the current `Role`, or an option to chose between the two in the helm release?

Our use case is  that we have a tooling namespace for all controllers and do not duplicate those controllers for each namespace.

**Comment by rasheedamir** [comment]
Sure @Mikulas

**Comment by rasheedamir** [comment]
@Mikulas how is it going? Do you need any help?

**Comment by rasheedamir** [comment]
@Mikulas its merged plz test it and let us know if you find any issues
