### ISSUE TITLE
[ENHANCE] Feature completeness for Pingdom create Alert API

### ISSUE THREAD

**Issue by karlderkaefer** [stakater/IngressMonitorController#553]
**Is your feature request related to a problem? Please describe.**
Hi we would like to use pingdom, however it seems stakater does not cover full [API spec](https://docs.pingdom.com/api/#tag/Checks/paths/~1checks/post) of pingdom. I have created following table for feature completeness

Pingdom API Feature | Supported by Stakater Ingress Monitor Controller | Description
-- | -- | --
sendnotificationwhendown | Supported (as SendNotificationWhenDown) | How many failed check attempts before notifying
notifywhenbackup | Supported (as NotifyWhenBackUp) | Set to 'false' to disable recovery notifications
auth | Supported (as BasicAuthUser) | Username and password, colon-separated.
paused | Supported | Set to 'true' to pause checks
requestheaders | Supported | Custom Pingdom request headers (e.g. {"Accept"="application/json"})
resolution | Supported | The Pingdom check interval in minutes
shouldcontain | Supported | Set to text string that must be present in the HTML code of the page
tags | Supported | Comma-separated set of tags to apply to check (e.g. "testing,aws")
teamids | Supported (as teamAlertContacts) | Teams to alert. Comma-separated integers.
integrationids | Supoorted (as alertIntegrations) | Integration identifiers. For example, [1,2,3].
userids | Supported (as alertContacts) | User identifiers. For example, 154325,465231,765871.
ssl_down_days_before | Supported | Treat as down if a certificate expires within specified days.
verify_certificate | Supported | Treat as down if an invalid/unverifiable certificate is found.
encryption | Supported by url scheme | Connection encryption.
custom_message | Not mentioned | Custom message added to email and webhook alerts.
ipv6 | Not mentioned | Use IPv6 instead of IPv4.
notifyagainevery | Not mentioned | Notify again every n result. 0 means no extra notifications.
postdata | Not mentioned | Data posted to the web page, e.g., submission data for forms.
probe_filters | Not mentioned | Filters for probe selections, e.g., "region: NA".
responsetime_threshold | Not mentioned | Triggers a down alert if the response time exceeds specified ms (not available for Starter and Free plans).
shouldnotcontain | Not mentioned | Target site should NOT contain this string.
type | Not mentioned | Type of check, e.g."http" "httpcustom" "tcp" "ping" "dns" "udp" "smtp" "pop3" "imap".

**Describe the solution you'd like**
I would like to create a PR. Please let me know if that makes sense from your point of view or any other tipps before I make effort. I see that you are [using external library ](https://github.com/stakater/IngressMonitorController/blob/6e51205ec683be1a0c152b71f5041c57afbf8236/pkg/monitors/pingdom/pingdom-monitor.go#L13C3-L13C48) that is [archived now](https://github.com/russellcardullo/go-pingdom). So I would need to create a fork first. we could maintain this in fork in SAP context.  

**Describe alternatives you've considered**
-

**Additional context**

**Comment by MuneebAijaz** [comment]
@karlderkaefer feel free to make a Pull request with required changes. For the library issue, could we find another library which could cover our usecases? That would be the best scenario.

**Comment by karlderkaefer** [comment]
@MuneebAijaz I'm afraid there is no other library to my knowledge. We have the openAPIv3 spec from pingdom you can download from the top https://docs.pingdom.com/api/ and code could be generated out of that spec. I think a new repository has to been built. However when #556 is merged, we have covered our requirements. Maybe I can create a new client in my freetime. Also we are in contact with the company solarwinds which has aquired pingdom. I'm asking them if they can provide a go client by themselves. This would be the ideal option.

**Comment by karlderkaefer** [comment]
I have added new golang client for pingdom https://github.com/karlderkaefer/pingdom-golang-client I can provide a PR to switch to new maintained client

**Comment by karl-johan-grahn** [comment]
@karlderkaefer what did solarwinds say about them providing a go client?

**Comment by karlderkaefer** [comment]
@karl-johan-grahn Solarwind will not provide a golang client implementation unfortunately. Maybe they can takeover the created client I will ask them again

**Comment by karlderkaefer** [comment]
Just to close this issue. Solarwind did not take over the golang client. They are working on their new pingdom / product version, not sure about the progress, but maybe we can expect a client then with new version. I do not actively work on the topic anymore. But I will maintain the new pingdom golang client if necessary. In theory the existing pingdom provider can also use the new golang client like pingdom transaction checks, to support all fields.

Feel free to reopen, if you want this feature
