### ISSUE TITLE
configuring monitor URL construction

### ISSUE THREAD

**Issue by gempesaw** [stakater/IngressMonitorController#61]
Howdy! Thanks for putting this controller together, it exactly solves the problem I'm working on at $WORK, so I'm quite grateful for all your hard work. I've noticed a few issues in our use case with the way the monitor URL is constructed, and I'd be happy to open PRs for either of these if you're interested.

- **protocol**: our ingress doesn't handle TLS on its own (we're running behind an ALB which terminates SSL, and using weave in our cluster for transparent pod-to-pod encryption), so our ingress manifest simply declares http endpoints. as a result, the logic for determing the protocol thinks we're doing plain http and uses the result from `iw.getHost()`, even though the actual endpoint is HTTPS. https://github.com/stakater/IngressMonitorController/blob/master/src/ingress-wrapper.go#L81-L85

- **ingressPort**: in the ingress, we define our service port by name, and reference it accordingly in the manifests for the ingress and service:

        apiVersion: extensions/v1beta1
        kind: Ingress
        metadata:
          name: test-app
        spec:
          rules:
          - host: example.host
            http:
              paths:
              - backend:
                  serviceName: test-app
                  servicePort: http
                path: /
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: test-app
        spec:
          ports:
          - name: http
            port: 80
            protocol: TCP
            targetPort: http
          selector:
            app: test-app
          type: ClusterIP

  As a result, the monitor url looks like http://example.host/http/healthcheck, when it could either be http://example.host:80/healthcheck, or simply http://example.host/healthcheck. https://github.com/stakater/IngressMonitorController/blob/master/src/ingress-wrapper.go#L95-L96

- **healthcheck path**: I noticed there's a monitorHealthAnnotation annotation that presumably I could put on my ingress to specify the healthcheck path, but it looks like it only gets appended to the existing `u.Path` value. One way to solve the ingressPort issue for us would be if this annotation /replaced/ the entire `u.Path` value, and it would also give more control over the healthcheck in general, if interested... https://github.com/stakater/IngressMonitorController/blob/master/src/ingress-wrapper.go#L107-L110

If you're interested in accepting PRs for customizing these, I imagine they could be top level options in the config map, or per-resource annotation overrides, depending on how you'd prefer to handle the options. And, if you're not interested in accepting incidental complexity, then no problem - we'll fork and go on our merry way. Thanks again!

**Comment by rasheedamir** [comment]
@gempesaw we are more than happy to accept PR's as all suggestions look very valid.

Please make small PR's and we take it from there!

**Comment by SunSparc** [comment]
Looks like I am having the same problem as the original poster, in their second bullet about the port being used even if it is a string. I run the IMC and it comes up with this for the Monitor URL: `https://domain.com/http/status.txt`

It also looks like this tool just looks for the first host on the ingress and uses the readiness probe for first container on it to determine the health of the ingress. Is that accurate?
