### ISSUE TITLE
Change operator work queue to a map of *Ingress object

### ISSUE THREAD

**Issue by rasheedamir** [stakater/IngressMonitorController#64]
Suggestion from @Mikulas 

Refactor the code; namely the operator work queue would be easier to work with if it was in fact a map with the *Ingress object. It would also simplify the code as it would remove the parsing (splitting) of the namespace/name key and would eliminate the API calls for getting an Ingress from key (name).

**Comment by gempesaw** [comment]
This may be solved by #75

**Comment by waseem-h** [comment]
Closed by #75
