### ISSUE TITLE
Leverage Github releases vs checking the binary into source control

### ISSUE THREAD

**Issue by drubin** [stakater/IngressMonitorController#68]
Currently, I notice there is an `out` directory which contains the binary data. Could we make use of GitHub releases to manage this rather?

**Comment by hazim1093** [comment]
@drubin Thank you for your feedback. 

We were looking into [goreleaser](https://github.com/goreleaser/goreleaser) to add it in our CI/CD flow for this purpose. 
You'll be seeing the binary in github releases soon. 

If you have any suggestions let us know.

**Comment by rasheedamir** [comment]
@faizanahmad055 I wonder what is needed to finish it? we have verified goreleaser in other repo?

**Comment by faizanahmad055** [comment]
@rasheedamir , yes we have tested this in stk. We just need to update its jenkinsfile to use goreleaser.

**Comment by rasheedamir** [comment]
@faizanahmad055 what is left to close this ticket?

**Comment by faizanahmad055** [comment]
Implemented via #126
