### ISSUE TITLE
K8S objects created during tests fail on simultaneous runs

### ISSUE THREAD

**Issue by hazim1093** [stakater/IngressMonitorController#74]
IMC creates several k8s objects while running its tests, and simultaneous tests running causes conflicts as the name of the objects is same.

Append a unique identifier with k8s objects created during tests so that there is no conflict while running multiple pipelines/tests simultaneously.

**Comment by hazim1093** [comment]
@waseem-h Have we tested this ? https://github.com/stakater/IngressMonitorController/pull/90

**Comment by waseem-h** [comment]
Made the name of the ingresses unique but uptime robot monitors should have unique url's i.e., 2 monitors having different name but same url cannot exist. So, the problem still persists with this change. We need to find a way to make url's unique for each ingress as well. Any suggestions @rasheedamir

**Comment by rasheedamir** [comment]
lets discuss over call today and then document on what we agree

**Comment by waseem-h** [comment]
Fixed in #101
