### ISSUE TITLE
Fix pingdom annotations

### ISSUE THREAD

**Issue by waseem-h** [stakater/IngressMonitorController#77]
Currently pingdom annotation are in format `monitor.stakater.com/pingdom/annotation` but this format is not allowed in kubernetes. We have to update the current pingdom annotations to the following format
```
monitor-name.monitor.stakater.com/annotation
```
i.e., `pingdom.monitor.stakater.com/annotation`

**Comment by rasheedamir** [comment]
The convention has been documented here:
https://github.com/stakater/IngressMonitorController/blob/master/docs/developing/conventions.md
