### ISSUE TITLE
Change in annotations doesn't reflect back to the Monitor

### ISSUE THREAD

**Issue by Anish-Gupta-Bose** [stakater/IngressMonitorController#79]
After creating the monitors, if one makes changes to the Ingress annotations related to the `IngressMonitorController`, they aren't reflected back to the Monitoring service.

**Comment by gempesaw** [comment]
Hmm, can you provide more information? 

- what annotations are you using, and what are you changing? 
- which monitoring service are you using? 
- what version are you using? 

(I'm not a maintainer, but I've contributed some changes to IMC annotations recently which may be related to your issue! But I can't tell from the information you've provided...)

**Comment by gempesaw** [comment]
oh, great! just wanted to be sure I hadn't created a new bug :)

**Comment by rasheedamir** [comment]
@Anish-Gupta-Bose anything which will improve the quality of this controller will be awesome! but just make a separate PR

**Comment by Anish-Gupta-Bose** [comment]
@rasheedamir I would make a separate PR, but since my fork has the StatusCake PR #76, I can't push it before that's closed. It would be great if the PR for StatusCake get's merged soon, cause I am using it for the cluster's here.

**Comment by Anish-Gupta-Bose** [comment]
Fix pushed in #88

**Comment by rasheedamir** [comment]
Closed by #88
