### ISSUE TITLE
Refactor configmap to secrets

### ISSUE THREAD

**Issue by rasheedamir** [stakater/IngressMonitorController#89]
Currently we take passwords and api keys as plain configmaps whereas they should be secrets.

Tasks:

- [ ] Refactor to convert them to secrets
- [ ] Update deployments and examples
- [ ] Update readme that its a breaking change and now info should be provided as a secret and not a configmap

**Comment by rayanebel** [comment]
Hello,
Do you have any update about this issue ?
I'm using IngressMonitorController with StatusCake and I'm really sad to expose the API KEY as plain text.

**Comment by rasheedamir** [comment]
@rayanebel we haven't got time yet to work on it; we will love to have a PR; can you work on it?

**Comment by kahootali** [comment]
@rasheedamir I believe it shouldn't be a breaking change and can have a parameter whether to mount from Configmap or Secrets, that defaults to Configmap else it will break for current users and one can change it if one wants secrets

**Comment by kahootali** [comment]
@rayanebel We are gonna start work on it soon
