### ISSUE TITLE
Add support for Updown in IngressMonitorController

### ISSUE THREAD

**Issue by rasheedamir** [stakater/IngressMonitorController#93]
Add support for updown in IMC to monitor the uptime of web applications / microservices deployed to kubernetes/openshift

https://updown.io/

Conventions to follow: https://github.com/stakater/IngressMonitorController/blob/master/docs/developing/conventions.md

**PR's are very welcome**

**Comment by aliartiza75** [comment]
I have created a PR #152 to add updown support in IngressMonitorController.

**Comment by aliartiza75** [comment]
Code for updown has been merged @kahootali I am closing this issue
