### ISSUE TITLE
Add support for Pingometer in IMC

### ISSUE THREAD

**Issue by rasheedamir** [stakater/IngressMonitorController#94]
Add support for pingometer in IMC to monitor the uptime of web applications / microservices deployed to kubernetes/openshift

https://pingometer.com/

Conventions to follow: https://github.com/stakater/IngressMonitorController/blob/master/docs/developing/conventions.md

**PR's are very welcome**

**Comment by usamaahmadkhan** [comment]
Pingometer is acquired by Uptime and uses Uptime's API. Added support for Uptime in PR #156
