### ISSUE TITLE
Add support for Uptime in IMC

### ISSUE THREAD

**Issue by rasheedamir** [stakater/IngressMonitorController#96]
Add support for Uptime in IMC to monitor the uptime of web applications / microservices deployed to kubernetes/openshift

https://uptime.com/

Conventions to follow: https://github.com/stakater/IngressMonitorController/blob/master/docs/developing/conventions.md

**PR's are very welcome**

**Comment by usamaahmadkhan** [comment]
Added support for Uptime in PR #156
